steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t" 
      - "gcr.io/$PROJECT_ID/neurapolis-ui:latest"
      - "-f"
      - "Dockerfile-streamlit"
      - "--build-arg"
      - "GITHUB_PAT=${_GITHUB_PAT}"
      - "."
    id: "Build Container Image"

  # Push the Docker image to GCR
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/neurapolis-ui:latest"
    id: "Push Image to Container Registry"

  # Deploy the image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "neurapolis-ui"
      - "--image"
      - "gcr.io/$PROJECT_ID/neurapolis-ui:latest"
      - "--region"
      - "europe-west3"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"
      - "--set-env-vars"
      - "OPENAI_API_KEY=${_OPENAI_API_KEY},LANGCHAIN_PROJECT=${_LANGCHAIN_PROJECT},LANGCHAIN_TRACING_V2=${_LANGCHAIN_TRACING_V2},LANGCHAIN_ENDPOINT=${_LANGCHAIN_ENDPOINT},AZURE_OPENAI_API_KEY=${_AZURE_OPENAI_API_KEY},AZURE_OPENAI_ENDPOINT=${_AZURE_OPENAI_ENDPOINT},AZURE_OPENAI_RESOURCE=${_AZURE_OPENAI_RESOURCE},COHERE_API_KEY=${_COHERE_API_KEY},OPENAI_API_VERSION=${_OPENAI_API_VERSION},DB_NAME=${_DB_NAME},DB_URI=${_DB_URI},DB_USERNAME=${_DB_USERNAME},AWS_ACCESS_KEY_ID=${_AWS_ACCESS_KEY_ID},AWS_DEFAULT_REGION=${_AWS_DEFAULT_REGION}"
      - "--set-secrets"
      - "LANGCHAIN_API_KEY=LANGCHAIN_API_KEY:latest,DB_PASSWORD=DB_PASSWORD:latest,AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY:latest"
    id: "Deploy Container on Google Cloud Run"

images:
  - "gcr.io/$PROJECT_ID/neurapolis-ui:latest"