FROM python:3.12-slim

WORKDIR /app

COPY pyproject.toml poetry.lock* ./
COPY src ./src

RUN apt-get update && apt-get install -y git

ARG GITHUB_PAT
RUN git config --global url."https://${GITHUB_PAT}@github.com/".insteadOf "https://github.com/"

RUN pip install --upgrade pip && \
    pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi

# Add a step to verify the lock file
RUN poetry lock --check

EXPOSE 8080

ENTRYPOINT ["streamlit", "run", "src/neurapolis_cognitive_architecture/app.py", "--server.port=8080", "--server.address=0.0.0.0"]
